### ISSUE TITLE
测试了下 报错了

### ISSUE THREAD

**Issue by bnnd** [qianjiahao/ES6-dev#1]
c:\Users\Jings\ES6-dev-master\node_modules\webpack-dev-server\node_modules\socke
t.io\node_modules\engine.io\node_modules\ws\node_modules\bufferutil>node "c:\nod
ejs\node_modules\npm\bin\node-gyp-bin\....\node_modules\node-gyp\bin\node-gyp.
js" rebuild
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。
MSBUILD : error MSB3428: 未能加载 Visual C++ 组件“VCBuild.exe”。要解决此问题，
1) 安装 .NET Fram
ework 2.0 SDK；2) 安装 Microsoft Visual Studio 2005；或 3) 如果将该组件安装到了
其他位置，请将其位置添加到系统
路径中。 [c:\Users\Jings\ES6-dev-master\node_modules\webpack-dev-server\node_mod
ule
s\socket.io\node_modules\engine.io\node_modules\ws\node_modules\bufferutil\buil
d\binding.sln]
gyp ERR! build error

**Comment by qianjiahao** [comment]
我搜了一下网上的解决方案：

设置npm的全局配置：

```
npm config set msvs_version 2010 --global
```

或者告诉npm使用Visual studio 2010版本

```
npm install socket.io --msvs_version=2010
```

最后补充一下，看到你的路径，应该是在windows环境下开发，建议弄个Linux或者oc x 环境，因为windows环境略坑啊。。。
